tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "wez/wezterm"
brew "bat"
brew "cloc"
brew "cookiecutter"
brew "coreutils"
brew "defaultbrowser"
brew "dotbot"
brew "duf"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "git"
brew "glances"
brew "go"
brew "htop"
brew "httpie"
brew "iperf"
brew "ipython"
brew "jq"
brew "loc"
brew "mariadb"
brew "mas"
brew "mypy"
brew "neovim"
brew "nmap"
brew "openssl@3"
brew "pipx"
brew "pnpm"
brew "poetry"
brew "portaudio"
brew "postgresql"
brew "pre-commit"
brew "procs"
brew "pyenv"
brew "pyright"
brew "python-launcher"
brew "rustup-init"
brew "shellcheck"
brew "starship"
brew "telnet"
brew "tldr"
brew "tmate"
brew "tmux"
brew "trash"
brew "tree"
brew "vercel-cli"
brew "virtualenv"
brew "watch"
brew "wget"
brew "youtube-dl"
cask "1password"
cask "blackhole-16ch"
cask "daisydisk"
cask "docker"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "protonvpn"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "wezterm"
cask "windscribe"
cask "zoom"
mas "AudioBookBinder", id: 413969927
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "Keynote", id: 409183694
mas "Microsoft PowerPoint", id: 462062816
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Reeder", id: 1529448980
mas "Refined GitHub", id: 1519867270
mas "Strongbox", id: 897283731
mas "Things", id: 904280696
mas "Wipr", id: 1320666476
