tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
brew "bottom"
brew "bpython"
brew "cloc"
brew "colima"
brew "cookiecutter"
brew "coreutils"
brew "defaultbrowser"
brew "duf"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "glances"
brew "go"
brew "htop"
brew "httpie"
brew "iperf"
brew "ipython"
brew "jq"
brew "loc"
brew "mariadb"
brew "mas"
brew "mypy"
brew "nmap"
brew "openssl@3"
brew "pipx"
brew "poetry"
brew "portaudio"
brew "postgresql"
brew "pre-commit"
brew "procs"
brew "pyenv"
brew "pyright"
brew "python-launcher"
brew "shellcheck"
brew "starship"
brew "telnet"
brew "tldr"
brew "tmate"
brew "tree"
brew "vercel-cli"
brew "virtualenv"
brew "watch"
brew "wget"
brew "youtube-dl"
cask "1password"
cask "blackhole-16ch"
cask "blackhole-64ch"
cask "daisydisk"
cask "docker"
cask "fig"
cask "fsnotes"
cask "google-chrome"
cask "iterm2-beta"
cask "openinterminal"
cask "qlstephen"
cask "quicklook-json"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "windscribe"
cask "wkhtmltopdf"
cask "yandex-cloud-cli"
cask "zoom"
mas "AudioBookBinder", id: 413969927
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "KeyKey", id: 1035137927
mas "Keynote", id: 409183694
mas "Microsoft PowerPoint", id: 462062816
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Reeder", id: 1529448980
mas "Things", id: 904280696
mas "Wipr", id: 1320666476
