#!/usr/bin/env bash

set -e

DOTBOT_DIR="dotbot"

git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
git submodule update --init --recursive "$DOTBOT_DIR"

"$DOTBOT_DIR/bin/dotbot" -c install.conf.yaml "${@}"
