#!/usr/bin/env bash
set -xeuo pipefail

bash -c '
set -xeuo pipefail
brew update
brew bundle --file Brewfile
brew upgrade --greedy-latest
brew bundle cleanup --file Brewfile --zap --force
brew cleanup
' &

bash -c '
set -xeuo pipefail
mise upgrade --yes
mise prune --yes
mise reshim --yes
' &

wait
