#!/usr/bin/env bash
set -xeuo pipefail

mise upgrade --yes
mise prune --yes &
mise reshim --yes &

/opt/homebrew/bin/brew update --auto-update
/opt/homebrew/bin/brew bundle --file Brewfile --cleanup --no-upgrade &
/opt/homebrew/bin/brew upgrade --greedy &
brew cleanup  # trigger _brew-dump
