[env]
_.path = ["~/code/dotfiles/bin", "~/.local/bin", "~/.cargo/bin"]
DIRENV_INITIALIZED = 1
LANG = "en_US.UTF-8"
LANGUAGE = "{{env.LANG}}"
LC_ALL = "{{env.LANG}}"
EDITOR = "code"
PYTHONDONTWRITEBYTECODE = 1
HOMEBREW_BUNDLE_NO_LOCK = 1
HOMEBREW_NO_ANALYTICS = 1
HOMEBREW_NO_AUTO_UPDATE = 1
HOMEBREW_NO_ENV_HINTS = 1
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK = 1
CPPFLAGS = "-I{{env.HOMEBREW_PREFIX}}/include"
LDFLAGS = "-L{{env.HOMEBREW_PREFIX}}/lib"
UV_NATIVE_TLS = "true"
DOTFILES_ROOT = "{{env.HOME}}/code/dotfiles"
STARSHIP_LOG = "error"
LOCAL_FISH_COMPLETION_DIR = "{{config_root}}/.config/fish/completions"

[hooks]
postinstall = 'mkdir -p "$LOCAL_FISH_COMPLETION_DIR"'

[tasks._install-fish-completions]
hide = true
run = '''
    {{arg(name="command")}} {{arg(name="completion_command", var=true)}} \
    > "$LOCAL_FISH_COMPLETION_DIR/{{arg(name="command")}}.fish"
'''

[tools]
bat = { version = "latest", postinstall = "mise run _install-fish-completions bat --completion fish" }
cargo-binstall = "latest"
cargo-insta = "latest"
delta = "latest"
fd = { version = "latest", postinstall = "mise run _install-fish-completions fd --gen-completions fish" }
fzf = "latest"
gh = { version = "latest", exe = "gh" }
go = "latest"
helmfile = { version = "latest", postinstall = "mise run _install-fish-completions helmfile completion fish" }
hyperfine = "latest"
hugo = "latest"
just = "latest"
killport = "latest"
node = "latest"
python = ["3.13", "3.12", "3.11", "3.10"]
ripgrep = { version = "latest", postinstall = "mise run _install-fish-completions rg --generate complete-fish" }
shellcheck = "latest"
starship = "latest"
tokei = "latest"
usage = "latest"
xh = { version = "latest", postinstall = "mise run _install-fish-completions xh --generate complete-fish && mkdir -p ~/.local/bin && ln (which xh) ~/.local/bin/xhs" }
yq = { version = "latest", postinstall = "mise run _install-fish-completions yq completion fish" }
zoxide = "latest"
"pipx:cookiecutter" = "latest"
"pipx:glances" = "latest"
"pipx:maturin" = "latest"
"pipx:poetry" = { version = "latest", postinstall = "mise run _install-fish-completions poetry completions fish" }
"pipx:pre-commit" = "latest"
"pipx:python-lsp-server[all]" = { version = "latest", uvx_args = "--with pylsp-mypy" }
"pipx:sqlfluff" = "latest"
"pipx:llm" = { version = "latest", uvx_args = "--with llm-ollama" }
"spm:sindresorhus/macos-trash" = "latest"
"cargo:mergiraf" = "latest"
rust = "latest"
"pipx:pypyp" = "latest"
helm = "latest"
uv = { version = "latest", postinstall = "mise run _install-fish-completions uv generate-shell-completion fish" }
java = "latest"
"npm:open-codex" = "latest"

[settings]
jobs = 8
experimental = true
trusted_config_paths = [
    "~/.config/mise/config.toml",
    "~/.config/mise/config.local.toml",
    "~/code/dotfiles/home/.config/mise/config.toml",
    "~/code/dotfiles/home/.config/mise/config.local.toml",
]
pipx = { uvx = true }
fetch_remote_versions_cache = "2d"
