[colors]
background = '#ffffff'
foreground = '#1f2328'
selection-background = '#bbdfff'
selection-foreground = '#1f2328'
cursor = '#1f2328'
black = '#24292f'
red = '#cf222e'
green = '#116329'
yellow = '#4d2d00'
blue = '#0969da'
magenta = '#8250df'
cyan = '#1b7c83'
white = '#6e7781'
light-black = '#57606a'
light-red = '#a40e26'
light-green = '#1a7f37'
light-yellow = '#633c01'
light-blue = '#218bff'
light-magenta = '#a475f9'
light-cyan = '#3192aa'
light-white = '#8c959f'
light-foreground = '#1F2328'
