editor = "/usr/local/bin/code"
confirm-before-quit = false

[adaptive-theme]
light = "github-light"
dark = "vscode-dark"

[window]
width = 1200
height = 800

[fonts]
size = 20
family = "FiraCode Nerd Font"
