[tools]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]
node = "lts"
go = "latest"
usage = "latest"
"pipx:maturin" = "latest"
"pipx:poetry" = "latest"
"pipx:pypi-command-line" = "latest"
"pipx:watchfiles" = "latest"

[settings]
experimental = true
