[env]
_.path = ["~/code/dotfiles/bin", "~/.local/bin", "~/.cargo/bin"]
DIRENV_INITIALIZED = 1
LANG = "en_US.UTF-8"
LANGUAGE = "{{env.LANG}}"
LC_ALL = "{{env.LANG}}"
EDITOR = "code"
PYTHONDONTWRITEBYTECODE = 1
HOMEBREW_BUNDLE_NO_LOCK = 1
HOMEBREW_NO_ANALYTICS = 1
HOMEBREW_NO_AUTO_UPDATE = 1
HOMEBREW_NO_ENV_HINTS = 1
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK = 1
CPPFLAGS = "-I{{env.HOMEBREW_PREFIX}}/include"
LDFLAGS = "-L{{env.HOMEBREW_PREFIX}}/lib"
UV_NATIVE_TLS = "true"
DOTFILES_ROOT = "{{env.HOME}}/code/dotfiles"

[tools]
bat = "latest"
cargo-binstall = "latest"
gh = { version = "latest", exe = "gh" }
go = "latest"
hadolint = "latest"
helmfile = "latest"
node = "latest"
python = ["3.13", "3.12", "3.11", "3.10", "3.9", "3.8"]
rust = "latest"
shellcheck = "latest"
usage = "latest"
yq = "latest"
"ubi:astral-sh/uv" = "latest"

"cargo:cargo-insta" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:hyperfine" = "latest"
"cargo:just" = "latest"
"cargo:killport" = "latest"
"cargo:mprocs" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:tokei" = "latest"
"cargo:xh" = "latest"
"cargo:zoxide" = "latest"
"npm:http-server" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:glances" = "latest"
"pipx:maturin" = "latest"
"pipx:poetry" = "latest"
"pipx:pre-commit" = "latest"
"pipx:python-lsp-server[all]" = { version = "latest", uvx_args = "--with pylsp-mypy" }
"pipx:sqlfluff" = "latest"
"spm:sindresorhus/macos-trash" = "latest"
"ubi:gohugoio/hugo" = "latest"
"ubi:junegunn/fzf" = "latest"


[settings]
experimental = true
trusted_config_paths = [
    "~/.config/mise/config.toml",
    "~/.config/mise/config.local.toml",
    "~/code/dotfiles/config/mise/config.toml",
    "~/code/dotfiles/config/mise/config.local.toml",
]
pipx_uvx = true
jobs = 8
