[tools]
python = ["3.12", "3.11", "3.10", "3.9", "3.8"]
node = "lts"
usage = "latest"
"cargo:cargo-insta" = "latest"
go = "latest"
"go:github.com/yusufcanb/tlm" = "latest"

[settings]
experimental = true
trusted_config_paths = [
    "~/.config/mise/config.toml",
    "~/code/dotfiles/config/mise/config.toml",
]
