[tools]
python = ["3.13", "3.12", "3.11", "3.10", "3.9", "3.8"]
node = "lts"
usage = "latest"
go = "latest"
"cargo:bat" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:eza" = "latest"
"cargo:git-delta" = "latest"
"cargo:hyperfine" = "latest"
"cargo:just" = "latest"
"cargo:killport" = "latest"
"cargo:mprocs" = "latest"
"cargo:procs" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:tokei" = "latest"
"cargo:xh" = "latest"
"cargo:zoxide" = "latest"
"cargo:fd-find" = "latest"
"npm:http-server" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:glances" = "latest"
"pipx:maturin" = "latest"
"pipx:pre-commit" = "latest"
"pipx:sqlfluff" = "latest"

[settings]
experimental = true
trusted_config_paths = [
    "~/.config/mise/config.toml",
    "~/code/dotfiles/config/mise/config.toml",
]
pipx_uvx = true
